Clearer Completed Assignments, Calendar Functionality, Color Picker, etc.
jsadowyj0/schoology-ext pull request #4
Opened 2020-09-26 03:28 UTC by Orion31Dev

- Completed assignments will now say "Completed" (or variation thereof) next to the due date.
- Manually mark (or unmark) assignments as complete in the assignment page
- The calendar will now show completed assignments
- Color picker to pick the color of completed assignments
- Probably more

2020-09-26 15:51 UTC, jsadowyj0 commented on manifest.json
> +  "name": "Schoology Completion Extension",
I don't think the name needs to be this verbose, I think we should keep it Schoology check. If you have a reason to change it let me know

2020-09-26 16:30 UTC, jsadowyj0 requested changes
So overall, you made significant changes, which I really like. My only gripe right now is I just do not think that the color picker is production-ready. It introduces a lot more issues than it solves right now. To sum it up, I think you should take out the color picker for now and just implement everything else. My opinion is that you should introduce the color picker when you are finished adding a lot of other features, so you have more experience because right no,w the implementation is very messy.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-assignment.js
Why delete that if statement? This makes it so the user does not have a bunch of error messages in their console on the alternate assignment submit page.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-assignment.js
> +    }
```suggestion
     const getDesc = () => {
       for (assignment of schoologyData) {
         if (assignment.id !== assignmentId) return;
         return assignment.desc
       }
    }
```
I feel like this implementation would be a lot cleaner.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-assignment.js
> +    setTimeout(checkCompleted, 500);
Instead of using the boolean `cancelInterval` you should make this a recursive function.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-calendar.js
> +document.styleSheets[0].insertRule(":root{--comp-color: #000000; --cal-border-color: #000000; --cal-text-color: #000000}");
Is there a cleaner way to go about this? I'm no master at CSS but can you not just include this at the beginning of the CSS document?

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-calendar.js
> +    updateColor();
This will cause a LOT of bugs. Not to mention everything needs to be wrapped in the jQuery document ready function because at this point the page has not even been loaded yet.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-calendar.js
> +    let completedElements = [];
```suggestion
    const completedElements = [];
```
you are not specifically assigning another value so you can change this to const.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-calendar.js
> +            'span.infotip').innerHTML.split('<')[0];
There has to be a cleaner way to do this, this seems very hacky.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-home.js
> -  'div.upcoming-events div.upcoming-event.course-event span a';
DO NOT DELETE THIS! You will see later what it does, the Schoology website actually has two assignment elements that are basically carbon copies of each other, except one is not visible. So the checkmarks go to the non-visible ones making it so the users can't see any checkmarks.

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-home.js
> +}, 500);
Please don't implement this into production

2020-09-26 16:30 UTC, jsadowyj0 commented on src/async-home.js
> +  let completedEle = [];
```suggestion
  const completedAssignments = [];
```
I would make the name more clear, and also you are using `let` way more than you need to. A rule of thumb in javascript is to use `const` unless you are specifically RE-assigning that variable in the future.

2020-09-27 02:09 UTC, Orion31Dev commented
@jsadowyj0 Tbh, I don't think any of what I wrote was very sustainable or future proof so I rewrote it all. I'm gonna close this PR and make a new one.

2020-09-27 02:09 UTC, closed without merging